### ISSUE TITLE
proje 3 malloc

### ISSUE THREAD

**Issue by yunusemreyazici** [gusanmaz/BMB311_OS#12]
merhaba hocam proje 3 ile çalışıyorum neredeyse bitti. fakat şöyle birşey var file open işlemlerinde mallocla bellekte yer ayırmam gerekiyor. henüz multithread şekilde çalışmıyor kodum. mallocla çok fazla alan ayırırsam programım yavaşlıyor fakat az yer ayırırsamda 1 sayısını bulamadan [segmentation fault ](zsh: segmentation fault) hatası alıyorum.

sorum şu ki programımın import edeceği maximum dosya boyutu nedir? ona göre mallocla bellekte yer ayırma işlevi yapacağım??

**Comment by gusanmaz** [comment]
`fgetc` ile dosyayi karakter karakter okursaniz dosya okuma icin `malloc` kullanmaniza gerek kalmaz. Bu sekilde yapilacak bir okuma elbette yavas olacaktir ama kabul edilecek bir cozumdur. 

**Asagida yazdiklarim bu projeden ekstra puan almak isteyenleri ilgilendiriyor.**

Okuma isini hizlandirmak icin `fgets` gibi fonksiyonlar kullanabilirsiniz. Bu durumda `malloc` fonksiyonu kullanmaniz gerekebilir. `malloc` fonksiyonu `NULL` degeri donduruyorsa bellek alani olusturma isi basarisizlikla sonuclandi demektir. `malloc`'un donus degerini kontrol ederek mumkun olan en buyuk bellek alanini olusturmaya calisan bir optimizasyon yapabilirsiniz.

Maximum dosya boyutunda bagimsiz calisabilecek bir kod yazmaya calisin. Ama kodlarinizi 2GB`in uzerinde dosyalarla kontrol etmeyecegimi soyleyebilirim.

```fakat az yer ayırırsamda 1 sayısını bulamadan [segmentation fault ](zsh: segmentation fault) hatası alıyorum.```
Bu kisimda yazdiklarin tuhaf geldi. `malloc` kullanimi ile bir yanlisin olabilir mi?

**Comment by yunusemreyazici** [comment]
macOS'dan kaynaklı sorun yaşıyormuşum, dediğiniz gibi fgetc kullandım malloc kullanmama gerek kalmadı hocam teşekkür ederim yanıtınız için 💯
