### ISSUE TITLE
işletim sistemleri proje2

### ISSUE THREAD

**Issue by atilaparyab** [gusanmaz/BMB311_OS#16]
Merhaba hocam

istediğiniz projede 15 konu var ve bizim grup 6 kişilik bir grup, şimdi biz bu 15 konuyu bu 6 kişi arasında paylaştıracak mıyız yoksa herkes tek bir konu mu anlatıcak?

**Comment by gusanmaz** [comment]
Merhaba Atilla. Yanlis repodasin! Bu repo gecen seneki dersin reposu. Sorunu https://github.com/gusanmaz/BMB311_OS_2023 burada sorabilir misin?

**Comment by atilaparyab** [comment]
Merhaba hocam
işletim sistemleri dersinde ikinci projede 15 konu var ve bizim grup 6
kişilik bir grup. Şimdi benim sorum biz bu 15 konuyu 6 kişi arasında
paylaştıracak mıyız yoksa herkes o konulardan sadece bir tane mi yapacak?
